### ISSUE TITLE
motion prop doesn't work, but the deprecated 'animation' prop does. However, it only accepts 'zoom.'

### ISSUE THREAD

**Issue by RayBans2111** [react-component/tooltip#254]
Hello,

I am using this component in order to render tooltips for my site. However, when I want to add an animation to the tooltip, no other animation name works other than 'zoom'. I tried playing around with the motion prop (Which isn't explained in the docs), and transitionName, but neither of those two work.

The zoom animation is a little too playful for my site, and I would just like to know how I can set a simple 'fade' animation instead. I tried looking into all the animation names, but the links I would visit were all dead ends. 

It would be great to know the proper way to setup an animation for the tooltip as I can't find a solid place that tells me how to.

**Comment by Johnrobmiller** [comment]
having "transitionName" prop was not a very good idea in the first place. It's extremely complex to try and do a simple animation, and to make matters worse, the documentation is very sparse and unhelpful.

**Comment by sgehrman** [comment]
yeah, where are the docs for the normal fade in?

**Comment by RayBans2111** [comment]
> yeah, where are the docs for the normal fade in?

I was never able to figure out a solution for this issue, and I ended up not using this library in the end, unfortunately.

**Comment by sambolias** [comment]
This does not seem like it should be closed. It seems like it would be possible to define the `motion` prop using https://reactjs.org/docs/animation.html#high-level-api-reactcsstransitiongroup, but that isn't very convenient. Is this something in the works, that will be documented when complete?
I did find that `transitionName` does work when set to `rc-tooltip-zoom`, which I assume is because some CSSTransitionGroups are defined in rc-tooltip. It would be convenient to have some presets set up like that.
