### ISSUE TITLE
Tooltips are not removed from DOM after stop of hover

### ISSUE THREAD

**Issue by Ahaiman** [react-component/tooltip#275]
After hover, the tooltip produces a div element in the DOM as expected, but once the hover stops, the element is still in the DOM and it doesn’t get destroyed. Which means that if I go all over the tooltips in a certain page, my DOM is full of div's of the tooltips.

I would expect that hovering will append tooltip to the elements in the DOM, and after stopping the hover, the element of the tooltip will be removed.

**Comment by cutesquirrel** [comment]
Hi Ahaiman,
I was like you when I used this component for the first time ! It's just because the tooltip isn't destroyed by default.
You have a prop `destroyTooltipOnHide` for that. If you set it to `true`, it will work as excepected.
The other option is to include the SCSS ('rc-tooltip/assets/bootstrap_white.css'), as the styles handles the hidding, even if the DOM element still exists.
Hope this helps
I think you can close this ticket ;)
